"""empty message

Revision ID: 49f8882cddad
Revises: 
Create Date: 2019-03-14 10:48:04.716591

"""
from alembic import op
import sqlalchemy as sa
import random
import time

# revision identifiers, used by Alembic.
revision = '49f8882cddad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    category = op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.CHAR(length=20), nullable=False),
    sa.Column('sub_table_name', sa.CHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sub_table_name')
    )
    category_game_machine = op.create_table('category_game_machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('disk', sa.Integer(), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('color', sa.CHAR(length=10), nullable=True),
    sa.Column('joy_stick_num', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('add_time', sa.Integer, nullable=True),
    sa.Column('remain_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    category_mobilephone = op.create_table('category_mobilephone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('color', sa.CHAR(length=10), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('add_time', sa.Integer, nullable=True),
    sa.Column('remain_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    user = op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    brand_table = op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('logo', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(
        user,
        [
            {
             'username':'admin',
             'password':"*90DEE064FB0C1803C7A3264512EFA911FA2F9638",
             'email':'admin@gmail.com'
            }
        ]
    )
    op.bulk_insert(
        category,
        [
            {
                'name': 'Phone',
                'sub_table_name': 'category_mobilephone'
            },
            {
                'name': 'Game Machine',
                'sub_table_name': 'category_game_machine' 
            }
        ]
    )
    brands = ['Apple', 'Samsung', 'Huawei', 'Google','Sony','Nokia','Honor','LG','OnePlus', 'Doro', 'Motorola', 'CAT', 'ZTE', 'BlackBerry', 'Xiaomi', 'HTC', 'Acer']
    images = [
        "http://dummyimage.com/100x100.jpg/5fa2dd/ffffff",
        "http://dummyimage.com/100x100.png/ff4444/ffffff",
        "http://dummyimage.com/100x100.bmp/ff4444/ffffff",
        "http://dummyimage.com/100x100.png/dddddd/000000",
        "http://dummyimage.com/100x100.jpg/cc0000/ffffff",
        "http://dummyimage.com/100x100.bmp/dddddd/000000",
        "http://dummyimage.com/100x100.jpg/cd12fc/000000",
        "http://dummyimage.com/100x100.jpg/cd12fc/ffffff",
        "http://dummyimage.com/100x100.jpg/12fc45/000000",
        "http://dummyimage.com/100x100.jpg/063b12/ffffff"
    ]

    brand_arr = []
    for brand in brands:
        attributes = {'name':brand, "logo":random.choice(images), "category":1}
        brand_arr.append(attributes)

    if len(brand_arr) > 0:
        op.bulk_insert(
            brand_table,
            brand_arr
        )
    phone_arr = []

    for brand_id in range(1, len(brands)+1 ):
        attributes = {'brand_id': brand_id, 'price': random.randint(1000,3000), 'remain_count': random.randint(10, 50), 'add_time': int(time.time())}
        phone_arr.append(attributes)
    
    if len(phone_arr) > 0:
        op.bulk_insert(
            category_mobilephone,
            phone_arr
        )

    game_machine_brands = ['IGT', 'Bally', 'Amaya', 'Microgaming', 'Arisocrat', 'Konami', 'WMS Gaming']
    brand_arr = []
    for brand in game_machine_brands:
        attributes = {'name':brand, "logo":random.choice(images), "category":2}
        brand_arr.append(attributes)

    if len(brand_arr) > 0:
        op.bulk_insert(
            brand_table,
            brand_arr
        )
        
    game_machine_arr = []

    for brand_id in range(len(brands)+1, len(game_machine_brands)+len(brands)+2 ):
        attributes = {'brand_id': brand_id, 'price': random.randint(100,1000), 'remain_count': random.randint(20, 100), 'add_time': int(time.time())}
        game_machine_arr.append(attributes)
    
    if len(game_machine_arr) > 0:
        op.bulk_insert(
            category_game_machine,
            game_machine_arr
        )
    op.create_index('part_of_name', 'brand', ['name'], mysql_length=5)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('category_mobilephone')
    op.drop_table('category_game_machine')
    op.drop_table('category')
    # ### end Alembic commands ###
